FROM public.ecr.aws/lambda/python:3.12

COPY apps/api/pyproject.toml ./
COPY apps/api/src ./src
COPY apps/web/out ./static
RUN python -m pip install . --target "${LAMBDA_TASK_ROOT}"

CMD ["opsweave_api.main.lambda_handler"]
